name: 'analytics_project'
version: '1.0.0'
config-version: 2

profile: 'analytics_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  analytics_project:
    marts:
      +materialized: table
    intermediate:
      +materialized: view
